### PR TITLE
Support tailwind 4

### PR DESCRIPTION
**Pull request by zcf0508**
Add support for tailwind 4.

### CODE REVIEW

**Comment by schoero** [comment]
Thank you for creating this PR.
I need to dive into tailwindcss v4 myself before I can review.  Also I think it is a bit too early to merge into main as tailwindcss v4 is still in alpha.

I will probably create a tailwindcss4 branch and merge into that one, so you don't have to keep your PR up to date.

I will get back to this soon.

**Comment by zcf0508** [comment]
Thanks for the reply.

I'm currently using Tailwind 4 for a new project, and I require this feature to enhance my code quality. Prioritizing support for Tailwind 4 will not only boost the project's visibility but also attract broader community feedback and support.

I will pay attention to the updates of Tailwind 4 and adjust the code in a timely manner.

**Comment by schoero** [comment]
I'm sorry for the delay. 

I saw a few things I wanted to change in your pull request, so I decided to merge into a different branch and make the changes myself instead of going back and forth in reviews many times.

I try to get out experimental support for tailwindcss v4 this weekend, thank you for getting things started  🙌

**Comment by zcf0508** [comment]
Thank you for the merge. I am very much looking forward to your next work.

**Pull request merged**
